services:
  - type: web
    name: wait
    plan: free
    runtime: image
    image:
      url: docker.io/tanin47/wait:0.2.1
    healthCheckPath: /healthcheck
    envVars:
      - key: PORT
        value: 9090
    autoDeploy: true
